# src/Acme/HelloBundle/Resources/config/routing.yml
home:
    path:  /
    defaults: { _controller: AppBundle:Home:index }

story:
    path:  /story
    defaults: { _controller: AppBundle:Story:index }

tutorial:
    path:  /tutorial
    defaults: { _controller: AppBundle:Tutorial:index }

rank:
    path:  /rank
    defaults: { _controller: AppBundle:Rank:index }

avatar_creator:
    path:  /avatar
    defaults: { _controller: AppBundle:Avatar:creator }
    
avatar_upload:
    path:  /avatar/upload
    defaults: { _controller: AppBundle:Avatar:upload }
    
team_apply:
    path:  /team/apply
    defaults: { _controller: AppBundle:Team:apply }
    
dashboard:
    path:  /dashboard
    defaults: { _controller: AppBundle:Dashboard:index }
    
inventory:
    path:  /inventory
    defaults: { _controller: AppBundle:Inventory:index }
    
map:
    path:  /map
    defaults: { _controller: AppBundle:Map:index }
    
overview:
    path:  /overview
    defaults: { _controller: AppBundle:Overview:index }

activity:
    path:  /activity
    defaults: { _controller: AppBundle:Activity:index }

radar:
    path:  /api/geo/json/radar/{lat}/{lng}/{a}
    defaults: { _controller: AppBundle:Map:getJson }
    
capture:
    path:  /capture
    defaults: { _controller: AppBundle:Capture:index }
    
scan:
    path:  /scan
    defaults: { _controller: AppBundle:Scan:index }
    
attack:
    path:  /attack
    defaults: { _controller: AppBundle:Attack:index }
    
build:
    path:  /build
    defaults: { _controller: AppBundle:Build:index }

construct:
    path:  /construct
    defaults: { _controller: AppBundle:Construct:index }

upgrade:
    path:  /upgrade
    defaults: { _controller: AppBundle:Upgrade:index }

tile: 
    path:  /tile
    defaults: { _controller: AppBundle:Tile:index }
    
tile_collect:
    path:  /tile_collect
    defaults: { _controller: AppBundle:Tile:collect }

store:
    path:  /store
    defaults: { _controller: AppBundle:Store:index }

buy:
    path:  /buy
    defaults: { _controller: AppBundle:Buy:index }

collector:
    path:  /collector
    defaults: { _controller: AppBundle:Collector:index }

collect:
    path:  /collect
    defaults: { _controller: AppBundle:Collect:index }

admin:
    path:  /admin
    defaults: { _controller: AppBundle:Admin:index }
    
admin_resetpg:
    path:  /admin/resetpg
    defaults: { _controller: AppBundle:Admin:resetpg }

admin_addtreasure:
    path:  /admin/addtreasure
    defaults: { _controller: AppBundle:Admin:addTreasure }